"""``to_python(graph)`` — emit a flat, runnable Python script from a graph.

This is Nodezator's "Export as Python" as a headless function. It walks the
graph in dependency order and, for each node, writes one assignment::

    _<node_id> = call_name(arg=<upstream var or literal>, ...)

* a **connected** input becomes a reference to the upstream node's variable
  (``_src`` for a single output, ``_src["socket"]`` for a named one),
* an **unconnected** input with a widget value becomes a ``repr()`` literal,
* imports declared on each node spec are collected, de-duplicated and emitted at
  the top so the script is self-contained and *calls the original functions*.

The output is ordinary Python: run it and you reproduce the graph's computation
without the engine or any UI. That is the round-trip guarantee.
"""

from __future__ import annotations

import keyword
import re
from typing import Any, Optional

from .graph import Graph
from .ordering import topological_order
from .registry import DEFAULT_REGISTRY, NodeRegistry
from .spec import is_multi_output

_SAFE = re.compile(r"\W")


def _var(node_id: str) -> str:
    """A valid Python identifier for a node's output variable."""
    cleaned = _SAFE.sub("_", node_id)
    if not cleaned or cleaned[0].isdigit() or keyword.iskeyword(cleaned):
        cleaned = f"n_{cleaned}"
    return f"_{cleaned}"


def _reference(graph: Graph, registry: NodeRegistry, edge) -> str:
    """Render a reference to the value flowing along ``edge``."""
    source_node = graph.node(edge.source)
    source_spec = registry.spec(source_node.type)
    var = _var(edge.source)
    if is_multi_output(source_spec):
        return f'{var}[{edge.source_output!r}]'
    return var


def to_python(
    graph: Graph,
    registry: Optional[NodeRegistry] = None,
    *,
    header: bool = True,
) -> str:
    """Emit a runnable Python script for ``graph``.

    Args:
        graph: the graph to export.
        registry: node-type registry; defaults to
            :data:`engine.registry.DEFAULT_REGISTRY`.
        header: prepend a short generated-by comment.
    """
    registry = registry or DEFAULT_REGISTRY
    order = topological_order(graph)

    # Map each target input to the edge feeding it, per node.
    stdlib_imports: list[str] = []
    third_party_imports: list[str] = []
    body: list[str] = []

    for node_id in order:
        node = graph.node(node_id)
        spec = registry.spec(node.type)

        imports = spec.get("imports") or {}
        for line, bucket in (
            (imports.get("stdlib"), stdlib_imports),
            (imports.get("thirdParty"), third_party_imports),
        ):
            if line and line not in bucket:
                bucket.append(line)

        connected = {e.target_input: e for e in graph.incoming(node_id)}

        args: list[str] = []
        for inp in spec["inputs"]:
            pname = inp["name"]
            if pname in connected:
                args.append(f"{pname}={_reference(graph, registry, connected[pname])}")
            elif pname in node.inputs:
                args.append(f"{pname}={node.inputs[pname]!r}")
            # else: rely on the function's own default.

        body.append(f"{_var(node_id)} = {spec['callName']}({', '.join(args)})")

    lines: list[str] = []
    if header:
        lines.append("# Generated by engine.to_python — a flat script equivalent to the graph.")
        lines.append("")
    if stdlib_imports:
        lines.extend(stdlib_imports)
        lines.append("")
    if third_party_imports:
        lines.extend(third_party_imports)
        lines.append("")
    lines.extend(body)
    return "\n".join(lines) + "\n"
