"""Write the golden example snapshots (and, on demand, the schema contract).

    uv run python freeze_schemas.py              # example snapshots only (committed)
    uv run python freeze_schemas.py --contract   # also emit the schema docs

`engine/schema.py` stays the source of truth for the contract; the JSON copies
are generated. We commit the *example* snapshots (a golden test of introspection
+ tracing) but not the contract files — those are regenerated when a non-Python
consumer (the Phase-4 frontend) needs them.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "examples" / "minimal"))

from engine import GRAPH_SCHEMA, NODE_SPEC_SCHEMA
from minimal import NODES, build_graph

OUT = Path(__file__).resolve().parent / "engine" / "schemas"


def _write(name: str, data: object) -> None:
    (OUT / name).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"wrote engine/schemas/{name}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    # Golden snapshots — generated by the engine from the decorated example.
    # Use a relative CSV path so the committed graph is machine-independent.
    _write("example.node-specs.json", {n.name: n.spec for n in NODES})
    _write("example.graph.json", build_graph("readings.csv").to_dict())

    # Contract docs — emitted only when asked (see module docstring).
    if "--contract" in sys.argv:
        _write("node-spec.schema.json", NODE_SPEC_SCHEMA)
        _write("graph.schema.json", GRAPH_SCHEMA)


if __name__ == "__main__":
    main()
