"""``to_python(graph)`` — emit a flat, runnable Python script from a graph.

Nodezator's "Export as Python" as a headless function. It binds the graph, walks
it in dependency order, and writes one assignment per node::

    _<node_id> = <fn>(arg=<upstream var or literal>, ...)

* a **connected** input becomes a reference to the upstream node's variable
  (``_src`` for a single output, ``_src['socket']`` for a named one),
* an **unconnected** input with a widget value becomes a ``repr()`` literal — a
  multi-line string spelled as the ADR 0020 block form, same helper the
  composite emitter uses, so both exports read alike,
* **positional-only** params are emitted positionally,
* imports are collected and **aliased on collision**: two nodes named ``total``
  from different modules import as ``total`` / ``total_2`` and call the alias, so
  the generated script never clobbers a name.

Run the output and you reproduce the graph's computation without the engine.
"""

from __future__ import annotations

import keyword
import re
from typing import Optional, Union

from .bind import BoundGraph, BoundNode, bind
from .graph import Graph
from .literals import INDENT, render_call, render_literal
from .registry import NodeRegistry
from .spec import is_multi_output

_SAFE = re.compile(r"\W")


def _var(node_id: str) -> str:
    cleaned = _SAFE.sub("_", node_id)
    if not cleaned or cleaned[0].isdigit() or keyword.iskeyword(cleaned):
        cleaned = f"n_{cleaned}"
    return f"_{cleaned}"


def _aliases(bound: BoundGraph) -> tuple[dict[str, str], list[str]]:
    """Assign each used node type a unique local alias; build import lines."""
    used: dict[str, dict] = {}
    for node in bound.nodes:
        used.setdefault(node.type, node.spec)

    alias_of: dict[str, str] = {}
    taken: set[str] = set()
    imports: list[str] = []
    for type_id, spec in used.items():
        base = spec["qualname"]
        alias, n = base, 1
        while alias in taken:
            n += 1
            alias = f"{base}_{n}"
        taken.add(alias)
        alias_of[type_id] = alias
        suffix = "" if alias == base else f" as {alias}"
        imports.append(f"from {spec['module']} import {base}{suffix}")
    return alias_of, imports


def _render_value(bound: BoundNode, param: str, arg_indent: str) -> str:
    if param in bound.wired:
        source, socket = bound.wired[param]
        var = _var(source.id)
        return f"{var}[{socket!r}]" if is_multi_output(source.spec) else var
    return render_literal(bound.literals[param], arg_indent)


def _arg_exprs(bound: BoundNode, arg_indent: str) -> list[str]:
    inputs = bound.inputs_spec
    provided = set(bound.wired) | set(bound.literals)
    parts: list[str] = []

    # positional-only prefix: contiguous run, gaps filled with defaults
    pos_only = [i for i in inputs if i["kind"] == "positionalOnly"]
    if pos_only:
        supplied = [k for k, i in enumerate(pos_only) if i["name"] in provided]
        last = max(supplied) if supplied else -1
        for k in range(last + 1):
            inp = pos_only[k]
            if inp["name"] in provided:
                parts.append(_render_value(bound, inp["name"], arg_indent))
            else:
                parts.append(
                    inp.get("defaultRepr") or render_literal(inp["default"], arg_indent)
                )

    for inp in inputs:
        if inp["kind"] == "positionalOnly":
            continue
        if inp["name"] in provided:
            parts.append(f"{inp['name']}={_render_value(bound, inp['name'], arg_indent)}")
    return parts


def to_python(
    graph: Union[Graph, BoundGraph],
    registry: Optional[NodeRegistry] = None,
    *,
    header: bool = True,
) -> str:
    """Emit a runnable Python script for ``graph`` (a Graph or a bound graph)."""
    bound = graph if isinstance(graph, BoundGraph) else bind(graph, registry)

    alias_of, imports = _aliases(bound)
    # Statements sit at column 0 here, so an expanded call's arguments indent one
    # level in — same shared rendering as the composite (ADR 0020 D7).
    body = [
        f"{_var(n.id)} = "
        f"{render_call(alias_of[n.type], _arg_exprs(n, INDENT), '')}"
        for n in bound.nodes
    ]

    lines: list[str] = []
    if header:
        lines += ["# Generated by engine.to_python — a flat script equivalent to the graph.", ""]
    if imports:
        lines += imports + [""]
    lines += body
    return "\n".join(lines) + "\n"
